# Generated by Django 3.2 on 2023-05-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
